apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  selector:
    matchLabels:
      app: vote-ui
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - name: vote-ui-cont
        image: docker.io/pipilacha/vote:7d68f0f869775f496296360d75d904f8882c6343
        ports:
        - containerPort: 80