apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  selector:
    matchLabels:
      app: vote-ui
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - name: vote-ui-cont
        image: docker.io/pipilacha/vote:4858347b7b1757756596b173fc2d55f72adfe507
        ports:
        - containerPort: 80